#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1LBYRPHlOrhSuaBFWYiup1S1gYZ5ayT4h/7rXHJax63bvnDislKtuEsxWz/P0e0QgvPX98G3hzS9xzFgrs0tM1FQX7JlfLY7sKX10ugp3V1BIJOBdLqsnl20emWP3TcMldQZaYm9DNsYVEL8VonS1okSi9aHsHU42iGTl7y    MBhJbj5YqVigu8XPCAFt4mt/3i9Pwjk5dBnxIIU8x+JvNRvSnConB/kMCz8NKNjsDv7X//8uLhfH96eV3Ty8OnzygDTvP9NysQt73sWyq+aOZNA1Athhc8ZaFisjLMXCYW9HEyDxGpH
